# ~ 301.59 MB
FROM ruby:2.6.10

# ~ 23.67 MB
# FROM ruby:2.6.10-alpine

# It did not work unfortunately, did not source ~/.bashrc. Default shell here is "/bin/sh" so far.
# Set bash as a default shell (double quote is must here).
# Once the default shell is bash, the \. ~/.bashrc will be run when new shell is opened.
# Check ~/.profile for clarification.
# SHELL ["/bin/bash", "-c"]

WORKDIR '/social_network_app'

COPY ./Gemfile ./

COPY ./Gemfile.lock ./

RUN bundle install

# Install nvm (node version manager)
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

# Install node js, newer version is having problems with webpacker.
RUN . ~/.bashrc && nvm install 14.0.0
